New Plugin Viper Search IOC in Viper Database
conix-security/BTG pull request #15
Opened 2017-10-24 15:03 UTC by IrootGeek

The plugin Viper can Search IOC [ MD5, SHA256 ] in Viper Database

2017-11-13 10:40 UTC, rmarsollier requested changes
Some minor things to change.

2017-11-13 10:40 UTC, rmarsollier commented on modules/viper.py
> +class viper:
class name needs upercase first letter

2017-11-13 10:40 UTC, rmarsollier commented on modules/viper.py
> +        respond = requests.post(server,headers={'User-agent': 'viper Connector'}, data= ioc)
Use user-agent defined in config.ini

2017-11-13 10:40 UTC, rmarsollier commented on modules/viper.py
> +        self.search_method = "Online"
switch to offline, viper servers are expected to be on local networks

2017-11-14 13:01 UTC, closed without merging

2017-11-14 13:02 UTC, IrootGeek commented
I update viper plugin